# sonar-project.properties
sonar.projectKey=portfolio
sonar.projectName=Portfolio CI/CD K8S
sonar.host.url=http://sonarqube:9000

sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/.git/**,**/build/**

# Desactiver le provisioning JRE automatique (evite les erreurs de telechargement)
sonar.scanner.skipJreProvisioning=true

sonar.javascript.node.maxspace=512
