# sonar-project.properties
sonar.projectKey=portfolio
sonar.projectName=Portfolio CI/CD K8S
sonar.host.url=http://sonarqube:9000

sonar.sources=frontend/src,backend
sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/dist/**,\
  **/.git/**,\
  **/build/**,\
  **/public/**

# Desactiver le provisioning JRE automatique
sonar.scanner.skipJreProvisioning=true

# Performance : desactiver SCM pour eviter les appels git par fichier
sonar.scm.disabled=true

# Memoire Node.js pour l'analyse JS/TS
sonar.javascript.node.maxspace=512

# Activer le cache d'analyse pour les builds suivants
sonar.analysisCache.enabled=true
