apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin123"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            # 🆕 SMTP Gmail
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: "smtp.gmail.com:587"
            - name: GF_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: smtp-user
            - name: GF_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: smtp-password
            - name: GF_SMTP_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: grafana-smtp-secret
                  key: smtp-user
            - name: GF_SMTP_FROM_NAME
              value: "Grafana Portfolio"
            - name: GF_SMTP_SKIP_VERIFY
              value: "false"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: grafana-data
          emptyDir: {}