apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
type: Opaque
stringData:
  smtp-user: "etablissementdinformatiqueacad@gmail.com"        # 🔴 Ton email Gmail
  smtp-password: "gddpfauhnrpqlcmp"    # 🔴 Mot de passe app 16 caractères